/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectdiyawaraimplementation;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Kasun
 */
public class LoginInterface extends javax.swing.JFrame {

    /**
     * Creates new form LoginInterface
     */
    public LoginInterface() {
        initComponents();
       // setTitle("Log in Administrator");
    }
    
    //Switch to another interface we use that dispose method
       public void dispose()
     {
           WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
           Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_loginadmin = new javax.swing.JButton();
        btn_loginadminreset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_remember = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        message = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("User name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Password");

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        btn_loginadmin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_loginadmin.setText("Log in");
        btn_loginadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginadminActionPerformed(evt);
            }
        });

        btn_loginadminreset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_loginadminreset.setText("Reset");
        btn_loginadminreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginadminresetActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        txt_remember.setText("Remamber password");
        txt_remember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rememberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(message, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_loginadmin)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_loginadminreset)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_remember)))
                        .addGap(119, 119, 119))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_remember))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_loginadminreset)
                            .addComponent(btn_loginadmin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(960, 635));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //validate the login username and password with database
    
    private void btn_loginadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginadminActionPerformed
    String user = txt_username.getText().trim();
    String pw = txt_password.getText().trim();
 
    
    Connection conn=null;
        PreparedStatement pstmt =null;
        ResultSet rs=null;
        
        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        conn =(Connection) DriverManager.getConnection("jdbc:mysql:///diyawaraimplementation1","root","");
        pstmt = (PreparedStatement) conn.prepareStatement("select * from logindb");
        //pstmt.setString(1, date);
        rs=pstmt.executeQuery();
        while(rs.next())
        {
          String userdb = rs.getString("username");
          String pwdb = rs.getString("password");
          String typ = rs.getString("type");
          
            if (user.equals(userdb) && pw.equals(pwdb)){
                if(typ.equals("1")){
                AdminDashBoard ad = new AdminDashBoard();
                ad.setVisible(true);
                }else if(typ.equals("2"))
                        {
                        EAorIEdashBoard ea = new EAorIEdashBoard();
                        ea.setVisible(true);
                        }
                else if(typ.equals("3")){
                AgriOfficerDashBoard ao = new AgriOfficerDashBoard();
                 ao.setVisible(true); 
                }
                else
                {
                
                JOptionPane.showMessageDialog(null, "Login Unsuccessfull");
                }
            } 
            
            
          
          
        }
        
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,e);
        }
        
        finally
        {
        try{
        conn.close();
        pstmt.close();
        rs.close();
        }  
        
        catch(Exception e)
        {
        
        }
        
        }
        

 /*if(txt_username.getText().equalsIgnoreCase("ad")&& txt_password.getText().equals("123")){
            if(txt_remember.isSelected())
            {
                dispose();
                AdminDashBoard ad = new AdminDashBoard();
                
                ad.setVisible(true);
                message.setText("Successfull");
               
            }
            else
            {
                message.setText("Successfull within remember");
                
                
            }
            
            }else
       	    {
               message.setText("Log in unsuccessfull");
              
	    }
            
       */    
        /*       
       String username = txt_username.getText();
       String password= String.valueOf(txt_password.getPassword());
       Connection conn= null;
       PreparedStatement pstmt = null;
       ResultSet rs = null;
       
       try
       {
       Class.forName("com.mysql.jdbc.Driver");
       conn =(Connection) DriverManager.getConnection("jdbc:mysql:///diyawaraimplementation1","root","");
       pstmt = (PreparedStatement) conn.prepareStatement("select * from login where username=?");
       pstmt.setString(1,username);
       rs=pstmt.executeQuery();
        while(rs.next())
        {
            if(password.equals(rs.getString("password")))
            {
                JOptionPane.showMessageDialog(null, "You are log in succesfull as Administrator!");
               
                //switch to admin dashboard
                dispose();
                AdminDashBoard adb = new AdminDashBoard();
                adb.setVisible(true);
                //dispose();   

            }
            
            else
                {
                JOptionPane.showMessageDialog(null, "Log in not successfull !");
                }
        }
       
       }
       
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,e);
       }
       */
    }//GEN-LAST:event_btn_loginadminActionPerformed

    //Reset the login 
    private void btn_loginadminresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginadminresetActionPerformed
        txt_username.setText("");
          txt_password.setText("");
    }//GEN-LAST:event_btn_loginadminresetActionPerformed

    private void txt_rememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rememberActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_loginadmin;
    private javax.swing.JButton btn_loginadminreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel message;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JCheckBox txt_remember;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
