/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectdiyawaraimplementation;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Kasun
 */
public class ManningOutPutCalc extends javax.swing.JFrame {

    /**
     * Creates new form ManningOutPutCalc
     */int radio;
    public ManningOutPutCalc() {
        initComponents();
    }
    
    public void dispose()
     {
           WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
           Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ta1 = new javax.swing.JTextField();
        ta2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manning Calculator");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Waterlevel ID");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Water amount");

        ta2.setText("Ac.ft");
        ta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ta2ActionPerformed(evt);
            }
        });

        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton1.setText("More Details");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        ta3.setColumns(20);
        ta3.setRows(5);
        jScrollPane1.setViewportView(ta3);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ta1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ta2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 218, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 402, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1)))
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(960, 635));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ta2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ta1.setText("");
        ta2.setText("Ac.ft");
        ta3.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String val = ta2.getText();
        String ID = ta1.getText();
     
        Connection conn=null;
        PreparedStatement pstmt =null;
        ResultSet rs=null;
        
        
        try{
        Class.forName("com.mysql.jdbc.Driver");
        conn =(Connection) DriverManager.getConnection("jdbc:mysql:///diyawaraimplementation1","root","");
        pstmt = (PreparedStatement) conn.prepareStatement("SELECT waterlevelid,H,LL,LR,b,S,n,height,r FROM tripisiumshape WHERE waterlevelid=2");
        
        rs=pstmt.executeQuery();
            
       
      
     
      //STEP 5: Extract data from result set
      while(rs.next()){
         //Retrieve by column name
          String waterlevelid  = rs.getString("waterlevelid");
         double H  = rs.getFloat("H");
         double LL  = rs.getFloat("LL");
         double LR  = rs.getFloat("LR");
         double b  = rs.getFloat("b");
         double S  = rs.getFloat("S");
         double height = rs.getFloat("height");
         double n  = rs.getFloat("n");
         double r  = rs.getFloat("r");
         
         double h = 2.0;    
        
        double tt = 0;
        double givenQ = Double.parseDouble(val);
        
        ManningOutPutCalc t = new ManningOutPutCalc();
         
        String decision = "T";
        if(decision == "T" )
        {            
             tt = t.tripeasiam(H,LL,LR,b,S,n,h );
            // double ttt = Double.parseDouble(tt);             
        }
        else
        {
            tt = t.round(r, h, S, n);
        }
        //System.out.println(Math.toDegrees(tt));
        //System.out.println(tt);
        double time = givenQ/tt;
        
        String timeS = Double.toString(Math.round(time));
        if(radio == 0)
        {
            ta3.append("Time: "+timeS+"s");
        }
        else
        {
            ta3.append("Time:\t"+timeS+"s"+"\n" + "**************Aditional Information**************\n" + "Max Higt:\t" + H+"m" + "\n" + "Bed Width:\t" + b+"m");
            
        }
        
      }
        }
      
       catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,e);
        }
        
        finally
        {
        try{
        conn.close();
        pstmt.close();
        rs.close();
        }  
        
        catch(Exception e)
        {
        
        }}
    }
        
         public double tripeasiam( double H, double LL, double LR, double b, double S,  double n, double h )
    {
        //Calculation part
        //degree of both side(radian)
        double DL = Math.acos(H/LL);
        double DR = Math.acos(H/LR);
        
        //Slope length
        double lL = h/Math.cos(DL);
        double lR = h/Math.cos(DR);
        
        double xL = h*Math.tan(DL);
        double xR = h*Math.tan(DR);
        
        //Top width at water lewel
        double t = b + xL + xR;
        
        //perimeter at water lewel
        double p = b + t + lL + lR;
        
        //Area of crossection of water
        double A = (h*(b+t))/2;
        
        //R value
        //double R = this.quantity(A, p, S, n);
        
        // Velosity
        //double V = (1.49 * (Math.pow(Math.cbrt(R), 2)) * Math.sqrt(S))/n;
        
        //double Q = V * A;// Quantity for 1 second
        double Q = this.quantity(A, p, S, n);
        
        /*//double radians = Math.toRadians(degrees);
           System.out.format("L\u03b8: %f\u2070%n",Math.toDegrees(DL));
           System.out.format("R\u03b8: %f\u2070%n",Math.toDegrees(DR));
           System.out.format("Left slop lenth: %f ft%n",lL);
           System.out.format("Right slope length: %f ft%n",lR);
          // System.out.format("%f%n",xL);
           //System.out.format("%f%n",xR);
           System.out.format("Top Width(at water level): %f ft%n",t);
           System.out.format("Perimeter at water lewel: %f ft%n",p);
           System.out.format("Area at water lewel: %f ft\u00b2%n",A);
           //System.out.println(Math.cbrt(8));
           //System.out.println(Math.pow(4,2));
           System.out.format("V: %f fts\u207b\u00b9%n",V);
           System.out.format("Q: %f ft\u00b3%n",Q);*/
            return Q;
    }
    public double round(double r, double h, double S, double n)
    {
        //Degree 
        double D = 2 * (Math.acos((r-h)/r));
        
        //length of chord(1/2)
        double x = r * Math.sin(D);
        
        //area of circle sector
        double A = 0.5 * D * Math.pow(r, 2);
        
        //Areaof relevent trangular
        double At = x * (r-h);
        
        //Area of chord
        double Ac = A - At;
        
        //perimeter
        double p = D * r;
        
        //R value
        //double R = this.quantity(Ac, p);
        //Quantity
        double Q =this.quantity(A, p, S, n);       
      
        return A;
    }
     public double quantity(double A, double p, double S,double n)
    {
        //R value
        double R = A/p;
        
        //Velocity
        double V = (1.49 * (Math.pow(Math.cbrt(R), 2)) * Math.sqrt(S))/n;
        
        // Quantity for 1 second
        double Q = V * A;
        
        return Q;
    
         
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        EAorIEdashBoard a = new EAorIEdashBoard();
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
         radio = 1;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManningOutPutCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManningOutPutCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManningOutPutCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManningOutPutCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManningOutPutCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ta1;
    private javax.swing.JTextField ta2;
    private javax.swing.JTextArea ta3;
    // End of variables declaration//GEN-END:variables
}
